# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e8b59014305a1aa8fe1005a9f6bb7885fe00ce4b9685fb8c15623c6b907b28f4e5152b379eea6f6b75a93bee22c5277aa05113540058d1bf5a9ea52e1945823

test:
  secret_key_base: 773c5f8247f539333c4bbf3d108d64c928fab246f6ff1ae22847759b936f449bdcc6045214dd33b4580f84d1ce81a5da5f2911d9c7540e514ee022974661d797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
